{% set name = "napari" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77acd0bea1e0fbfde5896c94108d03bfc932cb8de527f4b7ea14699434f83611

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - napari = napari.__main__:main

requirements:
  build:
    - pep517
    - setuptools_scm
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-image
    - vispy >=0.6.4
    - dask
    - cachey
    - zarr
    - fsspec
    - imageio
    - ipykernel
    - jupyter_client
    - qtpy
    - qtconsole
    - IPython
    - backcall
    - pluggy
    - PyOpenGl
    - PySide2
    - wrapt
    - numpydoc
    - napari-plugin-engine
    - napari-svg
    - tifffile

test:
  requires:
    - pytest
    - pytest-faulthandler
    - pytest-qt
    - xarray
    - pandas
    - pytest-ordering
    - pytest-timeout
    - zarr
  imports:
    - napari
  commands:
    - setx QT_API "pyside2"  # [win]
    - export QT_API=pyside2  # [unix]
    - which napari
    #- DISPLAY=localhost:1.0 xvfb-run -a bash -c 'napari --info'
    #- pytest --pyargs napari

about:
  home: http://napari.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a fast n-dimensional image viewer in Python

  description: |
    a fast n-dimensional image viewer in Python
  doc_url: http://napari.org
  dev_url: https://github.com/napari/napari

extra:
  recipe-maintainers:
    - jni
    - sofroniewn
    - kne42
    - royerloic
    - AhmetCanSolak
