{% set name = "napari" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77acd0bea1e0fbfde5896c94108d03bfc932cb8de527f4b7ea14699434f83611

build:
  skip: true  # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - napari = napari.__main__:main

requirements:
  build:
    - pep517
    - setuptools_scm
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - appdirs >=1.4.4
    - python
    - scipy >=1.2.0
    - scikit-image
    - vispy >=0.6.4
    - dask >=2.1.0
    - cachey >=0.2.1
    - zarr
    - fsspec
    - imageio >=2.5.0
    - importlib-metadata >=1.5.0  # [py<38]
    - ipykernel >=5.1.1
    - ipython >=7.7.0
    - jupyter_client
    - qtpy >=1.7.0
    - qtconsole >=4.5.1
    - IPython
    - backcall
    - pillow
    - pluggy
    - psutil >=5.0
    - pyopengl >=3.1.0
    - pyqt
    - pyyaml >=5.1
    - wrapt >=1.11.1
    - numpy >=1.16.0
    - numpydoc >=0.9.2
    - napari-plugin-engine >=0.1.5
    - napari-svg >=0.1.4
    - tifffile >=2020.2.16
    - toolz >=0.10.0

test:
  requires:
    - fsspec
    - pytest
    - pytest-faulthandler
    - pytest-qt
    - xarray
    - pandas
    - pooch
    - pytest-ordering
    - pytest-timeout
    - zarr
  imports:
    - napari
  commands:
    - setx QT_API "pyqt5"  # [win]
    - export QT_API=pyqt5  # [unix]
    - which napari
    #- DISPLAY=localhost:1.0 xvfb-run -a bash -c 'napari --info'
    #- pytest --pyargs napari

about:
  home: http://napari.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a fast n-dimensional image viewer in Python

  description: |
    a fast n-dimensional image viewer in Python
  doc_url: http://napari.org
  dev_url: https://github.com/napari/napari

extra:
  recipe-maintainers:
    - jni
    - sofroniewn
    - kne42
    - royerloic
    - AhmetCanSolak
