{% set name = "napari" %}
{% set version = "0.4.11" %}

package:
  name: napari-meta

source:
  git_url: https://github.com/napari/napari.git
  git_rev: v{{ version }}

build:
  number: 1

outputs:
  - name: {{ name }}
    version: {{ version }}
    build:
      noarch: python
      skip: true  # [not linux]
      number: 1
      script: {{ PREFIX }}/bin/python -m pip install . -vv
      entry_points:
        - napari = napari.__main__:main

    requirements:
      build:
        - python-build
        - setuptools_scm
      host:
        - python >=3.7
        - pip
        - setuptools_scm
      run:
        - python >=3.7

        # dependencies matched to pip
        - appdirs >=1.4.4
        - cachey >=0.2.1
        - certifi >=2020.6.20
        - dask >=2.1.0
        - imageio >=2.5.0
        - importlib-metadata >=1.5.0  # not needed for py>37 but keeping for noarch
        - jsonschema >=3.2.0
        - magicgui >=0.2.6
        - napari-console >=0.0.3
        - napari-plugin-engine >=0.1.9
        - napari-svg >=0.1.4
        - numpy >=1.16.5
        - numpydoc >=0.9.2
        - pillow
        - pint >=0.17
        - psutil >=5.0
        - pyopengl >=3.1.0
        - pyyaml >=5.1
        - pydantic >=1.8.1
        - qtpy >=1.7.0
        - scipy >=1.2.0
        - superqt >=0.2.2
        - tifffile >=2020.2.16
        - typing_extensions
        - toolz >=0.10.0
        - tqdm >=4.56.0
        - vispy >=0.6.4
        - wrapt >=1.11.1

        # additional dependencies for convenience in conda-forge
        - fsspec
        - pyqt
        - scikit-image
        - zarr

    test:
      requires:
        - hypothesis
        - fsspec
        - pytest
        - pytest-faulthandler
        - pytest-qt
        - xarray
        - pandas
        - pooch
        - pytest-timeout
        - zarr
      imports:
        - napari
      commands:
        - setx QT_API "pyqt5"  # [win]
        - export QT_API=pyqt5  # [unix]
        - which napari
        #- DISPLAY=localhost:1.0 xvfb-run -a bash -c 'napari --info'
        #- pytest --pyargs napari

  - name: napari-menu
    version: {{ version }}
    build:
      skip: true  # [not win]
      number: 1
      script:
        - {{ RECIPE_DIR }}\install_menu.bat  # [win]
    requirements:
      run:
        - napari {{ version }}.*
    test:
      imports:
        - napari
    about:
      home: http://napari.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: provides menu icons for napari
      description: provides menu icons for napari
      doc_url: http://napari.org
      dev_url: https://github.com/napari/napari

about:
  home: http://napari.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a fast n-dimensional image viewer in Python
  description: a fast n-dimensional image viewer in Python
  doc_url: http://napari.org
  dev_url: https://github.com/napari/napari

extra:
  feedstock-name: napari
  recipe-maintainers:
    - jni
    - sofroniewn
    - kne42
    - royerloic
    - AhmetCanSolak
    - tlambert03
    - jaimergp
