{% set name = "napari" %}
{% set version = "0.4.13a" %}
{% set build = 4 %}
package:
  name: napari-meta

source:
  git_url: https://github.com/jaimergp/napari.git
  git_rev: conda-bundle-poc

build:
  number: {{ build }}

outputs:
  - name: {{ name }}
    version: {{ version }}
    build:
      noarch: python
      skip: true  # [not linux]
      number: {{ build }}
      string: "pyh{{ PKG_HASH }}_{{ build }}_{{ qt_bindings }}"
      script: PIP_NO_INDEX=True PIP_NO_DEPENDENCIES=True PIP_NO_BUILD_ISOLATION=False PIP_IGNORE_INSTALLED=True PYTHONDONTWRITEBYTECODE=True {{ PREFIX }}/bin/python -m pip install . -vv
      entry_points:
        - napari = napari.__main__:main

    requirements:
      build:
        - pep517
        - setuptools_scm
      host:
        - python >=3.7
        - pip
        - setuptools_scm
      run:
        - python >=3.7

        # dependencies matched to pip
        - appdirs >=1.4.4
        - cachey >=0.2.1
        - certifi >=2020.6.20
        - dask >=2.15.0
        - imageio >=2.5.0
        - importlib-metadata >=1.5.0  # not needed for py>37 but keeping for noarch
        - jsonschema >=3.2.0
        - magicgui >=0.3.0
        - napari-console >=0.0.4
        - napari-plugin-engine >=0.1.9
        - napari-svg >=0.1.4
        - numpy >=1.18.5
        - numpydoc >=0.9.2
        - pillow
        - pint >=0.17
        - psutil >=5.0
        - pyopengl >=3.1.0
        - pyyaml >=5.1
        - pydantic >=1.8.1
        - qtpy >=1.7.0
        - scipy >=1.2.0
        - superqt >=0.2.2
        - tifffile >=2020.2.16
        - typing_extensions
        - toolz >=0.10.0
        - tqdm >=4.56.0
        - vispy >=0.6.4
        - wrapt >=1.11.1

        # additional dependencies for convenience in conda-forge
        - fsspec
        - scikit-image
        - zarr
        - {{ qt_bindings }}

    test:
      requires:
        - hypothesis
        - fsspec
        - pytest
        - pytest-faulthandler
        - pytest-qt
        - xarray
        - pandas
        - pooch
        - pytest-timeout
        - zarr
      imports:
        - napari
      commands:
        - setx QT_API "pyqt5"  # [win]
        - export QT_API=pyqt5  # [unix]
        - which napari
        #- DISPLAY=localhost:1.0 xvfb-run -a bash -c 'napari --info'
        #- pytest --pyargs napari

  - name: napari-menu
    version: {{ version }}
    build:
      noarch: python
      # we only need to build this once
      skip: true  # [qt_bindings == 'pyside2']
      number: {{ build }}
      script:
        - mkdir -p "${PREFIX}/Menu"
        - sed "s/__PKG_VERSION__/{{ PKG_VERSION }}/" "{{ RECIPE_DIR }}/menu.json" > "{{ PREFIX }}/Menu/napari.json"
        - cp "{{ SRC_DIR }}/napari/resources/logo.png" "{{ PREFIX }}/Menu/napari.png"
        - cp "{{ SRC_DIR }}/napari/resources/icon.icns" "{{ PREFIX }}/Menu/napari.icns"
        - cp "{{ SRC_DIR }}/napari/resources/icon.ico" "{{ PREFIX }}/Menu/napari.ico"
    requirements:
      build:
        - sed     # [unix]
      run:
        - napari {{ version }}.*
    test:
      imports:
        - napari
      commands:
        - test -f ${CONDA_PREFIX}/Menu/napari.json

    app:
      entry: python -m napari
      icon: "{{ SRC_DIR|replace('\\', '/') }}/napari/resources/logo.png"
      summary: a fast n-dimensional image viewer in Python
      own_environment: True

    about:
      home: http://napari.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: provides menu icons for napari
      description: provides menu icons for napari
      doc_url: http://napari.org
      dev_url: https://github.com/napari/napari

about:
  home: http://napari.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a fast n-dimensional image viewer in Python
  description: a fast n-dimensional image viewer in Python
  doc_url: http://napari.org
  dev_url: https://github.com/napari/napari

extra:
  feedstock-name: napari
  recipe-maintainers:
    - jni
    - sofroniewn
    - kne42
    - royerloic
    - AhmetCanSolak
    - tlambert03
    - jaimergp
